Milestone #3
kensayo/microv-wk3-newsweek pull request #10
Opened 2021-02-04 22:38 UTC by kensayo

2021-02-05 10:47 UTC, Spayco commented
Hello, you can fix merge conflicts by doing `git pull origin main`, the files that have conflicts (in your case, index.html, and styles.css) would be changed and tells you where the conflict is, you can follow [this video](https://youtu.be/JtIX3HJKwfo) to see how to handle those changes, hope this helps, 



Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-05 11:15 UTC, PhillipUg requested changes
Hey team, 👋

You have done an amazing job implementing the requirements for this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [ ] If you need some assistance with your project or are having a hard time understanding something. Kindly feel free to schedule a call with a full-time TSE [using this link](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-#). Or you can reach out to any TSE on slack, we shall gladly help. In future projects, you don't need to submit your project for review if you're aim is to get assistance. Only, submit your project for review, if you feel its complete and ready to be reviewed.
- [ ] Secondly, its better you don't keep closing and opening new pull requests until project completion/approval. It causes a lot of confusion for us the reviewers. except for the case of this bootstrap project where all milestones 1, 2 & 3 should all be reviewed on the same pull request, while you're completing other projects unless a project or milestone is approved, please, keep submitting the same pull request, don't create another.

#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime** or
 <a href="mailto:phillipmusiime@gmail.com"> <img alt="gmail" src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social" target="_blank"></a> &nbsp; &nbsp; [![Twitter Follow](https://img.shields.io/twitter/follow/Phillip_Ug?style=social)](https://twitter.com/intent/follow?screen_name=Phillip_Ug) &nbsp; &nbsp; [![GitHub followers](https://img.shields.io/github/followers/phillipug?label=Follow&style=social)](https://github.com/PhillipUg)

2021-02-05 16:46 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] some images aren't loading, please fix that
- [x] Article images should be links
* [ ] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] Sponsored Insight articles are centered in the tablet view

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-02-05 16:46 UTC, Spayco commented on styles.css
> +}
- [ ] use `d-none` Bootstrap class instead of this

2021-02-05 18:02 UTC, kensayo commented
> # Changes Requested
> Hello Team! 👋
> Awesome job so far!! 👍 you still need to make some changes though!
> 
> ## Required Changes ♻️
> * [ ]  some images aren't loading, please fix that
> * [x]  Article images should be links
> 
> * [ ]  Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> * [x]  Sponsored Insight articles are centered in the tablet view
> 
> ### please make the appropriate changes and ask for another code review ✔️
> Happy Coding!
> 
> Best,
> Aziz Mejri
> _contact me on [twitter](https://twitter.com/iSpaYco) or slack (@Spayco) if you need any help_

All issues fixed, I wasn't able to find issues with image loading.

2021-02-05 22:32 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)
### Hello @kensayo and @craigs40 :balloon: :lollipop: 

### Thank you for working on the changes requested by the previous reviewers :medal_sports: :medal_sports: your project looks very similar to the original and there aren't missing sections, claps for the good work done so far :clap: :clap: :clap: let's work on the following changes :construction_worker: :construction_worker: 

### General

- [ ] NOT make [common mistakes](https://speckyboy.com/good-bad-css-practices) in your CSS styles
> I put comments directly in your CSS file where selectors were being repeated, create classes so you keep your CSS code DRY.

### Implementation requirements

* [x] Use Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options))

> you should use bootstrap classes and the CSS file should be as small as possible so let's use bootstrap classes for the following selectors:
- list-style: none
- height: auto
- text-decoration: none;
- color: (black, white, red, blue)
- background-color: (black, white, red, blue)
- display: (all that applies)
- justify-content: (all that applies)
- position: (all that applies)
- font-size: (al that applies)

### All Milestone requirements

#### Mobile Screens
##### Navbar
- [ ] The login, SUBSCRIBE button, and hamburger menu need to be aligned to the rightmost part of the navbar, also the Newsweek logo should be bigger and the red background (the navbar itself) should be smaller in height, also it should take the whole screen width, no white spaces should be showing left and right.
- Clone
![image](https://user-images.githubusercontent.com/52209067/107084324-8488c300-67bc-11eb-8f43-ca567a7cacf8.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/107084618-e6e1c380-67bc-11eb-8a4d-a039f32521b6.png)
##### Repeating sections
- [ ] Several of your sections are being repeated in this screen size there should be one of each section and the order should be respected: 
- Clone (wrong order)
TOP STORY -> FEATURED STORIES -> THE DEBATE -> OPINION -> SPONSOR INSIGHT / RANKINGS -> MORE STORIES -> MY TURN -> CULTURE & TRAVEL -> FREE SIGN UP form -> SPONSOR INSIGHT / RANKINGS  -> FEATURED STORIES -> SPONSOR INSIGHT / RANKINGS -> TOP STORY -> MY TURN -> CULTURE & TRAVEL  -> MORE STORIES -> LATEST NEWS -> THE DEBATE -> OPINION -> SPONSOR INSIGHT / RANKINGS -> FREE SIGN UP form -> SPONSOR INSIGHT / RANKINGS -> IN THE MAGAZINE -> EDITOR'S PICK -> Main articles (US, World, Bussiness, etc) -> SUBSCRIBE -> NEWSLETTER
- Original (right order)
TOP STORY -> FEATURED STORIES -> THE DEBATE -> OPINION -> SPONSOR INSIGHT / RANKINGS -> MORE STORIES -> LATEST NEWS -> MY TURN -> CULTURE & TRAVEL -> FREE SIGN UP form -> SPONSOR INSIGHT / RANKINGS -> IN THE MAGAZINE -> EDITOR'S PICK -> Main articles (US, World, Bussiness, etc) -> SUBSCRIBE -> NEWSLETTER 
##### Main news sections (U.S., World, etc.)
- [ ] The images of the small articles should take 60% of the screen width, they should be aligned with the big articles and there should be more margin separating the big articles from the small ones
- Clone
![image](https://user-images.githubusercontent.com/52209067/107086219-4e007780-67bf-11eb-8b2d-abf295dc2f12.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/107086270-62dd0b00-67bf-11eb-852d-d7b5a8a48c67.png)
##### SUBSCRIBE
- [ ] The images, text and subscribe button should be centered and the bold text should be on top of the images
- Clone
![image](https://user-images.githubusercontent.com/52209067/107086390-8ef88c00-67bf-11eb-9978-1341b1a53d04.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106070333-e31db500-60c9-11eb-8ef9-210903ab4d0a.png)
##### NEWSLEETTER
- [ ] The image should be on top and take the whole section width and half of the section height, the text should be centered, and the email input field next to the FREE SIGN UP button
- Clone
![image](https://user-images.githubusercontent.com/52209067/107086445-a5064c80-67bf-11eb-9ea4-25f4925e933e.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106072842-8a9ce680-60ce-11eb-8fd0-dacf10a73207.png)
##### Footer
- [ ] The bottom links should be aligned with the NEWSWEEK logo on the left
Clone
![image](https://user-images.githubusercontent.com/52209067/107086755-0e865b00-67c0-11eb-916c-c1205d7cd50c.png)
Original
![image](https://user-images.githubusercontent.com/52209067/107086811-1fcf6780-67c0-11eb-8666-01b88e80919c.png)
#### Tablet Screens
##### Navbar
- [ ] Should be small in this screen size and contains only the NEWSWEEK logo at the leftmost part and the LOGIN link SUBSCRIBE button and hamburger menu at the rightmost part
- Clone
![image](https://user-images.githubusercontent.com/52209067/107087370-f531de80-67c0-11eb-8ddf-25a15a9c6239.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/107087422-0844ae80-67c1-11eb-9cb3-363299c48cf2.png)
##### Main articles (US, World, Business, etc.)
- [ ] The aside articles should have less margin on the left with the main articles **Fix it in Desktop screens too**
Clone
![image](https://user-images.githubusercontent.com/52209067/107087969-dda72580-67c1-11eb-9d34-5a80b48ee535.png)
Original
![image](https://user-images.githubusercontent.com/52209067/107088006-ec8dd800-67c1-11eb-8022-0c56b2a5556d.png)
##### SUBSCRIBE 
- [ ] The SUBSCRIBE button should be aligned to the left like the upper text **Fix it also for Desktop screens**
- Clone
![image](https://user-images.githubusercontent.com/52209067/107088122-16df9580-67c2-11eb-9ba8-37d7b25781a6.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106076765-d43cff80-60d5-11eb-8725-6c1b8482cec7.png)
##### NEWSLETTER
- [ ] The email input and FREE SIGN UP button should be next to each other 
Clone
![image](https://user-images.githubusercontent.com/52209067/107088250-47273400-67c2-11eb-8073-373876ee3522.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106077333-f8e5a700-60d6-11eb-9f32-9f27530e29ed.png)
#### Desktop Screens
##### Navbar
- [ ] The links should be better distributed in the space right now they look centered in the Navbar but they should look justified
- Clone
![image](https://user-images.githubusercontent.com/52209067/107088492-a6854400-67c2-11eb-9b11-a7bd0cf06ec7.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/107088536-b56bf680-67c2-11eb-98da-337643b05ee8.png)
#### All Screens
##### LATEST NEWS
- [x] The Heading of this section should be written in all caps
- Clone
![image](https://user-images.githubusercontent.com/52209067/107092236-d3d4f080-67c8-11eb-8f8c-c514fa17fbea.png)
Original
![image](https://user-images.githubusercontent.com/52209067/107092278-e94a1a80-67c8-11eb-9d7b-f133b777662b.png)
##### SPONSORED INSIGHT/ RANKINS
- [ ] The images for these sections aren't showing and also the blue heading should be written with all caps
- Clone
![image](https://user-images.githubusercontent.com/52209067/107092372-15fe3200-67c9-11eb-82e4-97580786cd03.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106067427-40af0300-60c4-11eb-99a4-f9a65dfd8f14.png)
##### Main articles (U.S., World, Bussiness)
- [ ] The headings for these sections should be surrounded by an `<h>` tag
##### SUBSCRIBE and NEWSLETTER
- [x] The headings for these sections should be written in all caps
Clone
![image](https://user-images.githubusercontent.com/52209067/107094069-fddbe200-67cb-11eb-8f82-39032522129c.png)
Original
![image](https://user-images.githubusercontent.com/52209067/107094098-0d5b2b00-67cc-11eb-9598-58b4789c2795.png)

### That's it, team!  :raised_hands: 
### Please :pray:  do the changes :technologist: :technologist:  and submit back for a code review when you are done :memo: 
Any question? ask  [...]

2021-02-05 22:32 UTC, euqueme commented on index.html
> +          <a class="text-danger fw-bold inMagTitle" href="#">Tech & Science</a>
- [ ] The heading should be surrounded by an `<h>` tag

2021-02-05 22:32 UTC, euqueme commented on index.html
> +          <a class="text-danger fw-bold inMagTitle" href="#">Business</a>
- [ ] The heading should be surrounded by an `<h>` tag

2021-02-05 22:32 UTC, euqueme commented on index.html
> +          <a class="text-danger fw-bold inMagTitle" href="#">World</a>
- [ ] The heading should be surrounded by an `<h>` tag

2021-02-05 22:32 UTC, euqueme commented on index.html
> +          <a class="text-danger fw-bold inMagTitle" href="#">U.S.</a>
- [ ] The heading should be surrounded by an `<h>` tag

2021-02-06 11:10 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 
- Great work improving on most of the issues brought up earlier by the previous TSE!

## However, there are some changes required 👀 🧰 🔨 🔧 
- On mobile view some of your sections display stretched or distorted images. Please fix them: 
![image](https://user-images.githubusercontent.com/2739245/107116424-c0616e00-6838-11eb-938e-af386139f0ab.png)
![image](https://user-images.githubusercontent.com/2739245/107116428-cce5c680-6838-11eb-9f25-4da6c762c275.png)

- On tablet mode some of the thumbnails on the right side here are also stretched. Please fix them as well:
![image](https://user-images.githubusercontent.com/2739245/107116446-f0a90c80-6838-11eb-9abb-0fa4ed913e04.png)

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-02-07 17:21 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2021-02-07 17:32 UTC, merged